[package]
name = "vulkano-test"
version = "0.1.0"
edition = "2024"

[dependencies]
vulkano = { version = "*", default-features = true }
vulkano-shaders = "*"
winit = { version = "*", default-features = true }
